version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
    rust: "1.61"
  jobs:
    pre_build:
      - cp CHANGELOG.md docs/source/changelog.md
      - sed 's/\.\.\./pass/g' hugedict/hugedict/rocksdb.pyi > hugedict/hugedict/rocksdb.py

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: docs/package-requirements.txt
